name: Casa Elevada
favicon: null
layout_spectrum: 0.36721653514541686
typography_spectrum: 0.7004635420162231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191919'
    - '#c5c5c5'
    - '#676767'
    - '#484848'
  brandStrength: 0.3125
  lightness: 0.6186682470142841
  saturation: 0.6592633409891278
  rhythmicContrast: 0.5555531219579279
purpose: []
