typography_spectrum: 0.06796
color:
  brandColors:
    - '#ffffff'
    - '#191919'
    - '#c5c5c5'
    - '#676767'
    - '#484848'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Casa Elevada
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Materia Negra
    id: 633b0cfc-bfed-4c54-9c31-717dd567aef3
    type: content
favicon: null
title: Surf / Shred / Create / Elevate
description: Surf / Shred / Create / Elevate
purpose: []
